SET FOREIGN_KEY_CHECKS=0

DROP TABLE IF EXISTS `OA_ROLE` CASCADE
;

DROP TABLE IF EXISTS `OA_USER` CASCADE
;

CREATE TABLE `OA_ROLE`
(
	`RID` INT NOT NULL AUTO_INCREMENT ,
	`RNAME` VARCHAR(50),
	`UUID` INT,
	CONSTRAINT `PK_Table1` PRIMARY KEY (`RID`)
)
;

CREATE TABLE `OA_USER`
(
	`UUID` INT NOT NULL AUTO_INCREMENT ,
	`UNAME` VARCHAR(255),
	`UPWD` VARCHAR(255),
	`STATUS` TINYINT,
	`SEX` TINYINT,
	`ADDRESS` TEXT,
	CONSTRAINT `PK_OA_USER` PRIMARY KEY (`UUID`)
)
;

ALTER TABLE `OA_ROLE` 
 ADD INDEX `IXFK_OA_ROLE_OA_USER` (`UUID` ASC)
;

ALTER TABLE `OA_ROLE` 
 ADD CONSTRAINT `FK_OA_ROLE_OA_USER`
	FOREIGN KEY (`UUID`) REFERENCES `OA_USER` (`UUID`) ON DELETE Restrict ON UPDATE Restrict
;

SET FOREIGN_KEY_CHECKS=1
